content:
  - name: blog
    label: Blog
    type: collection
    path: _posts
    fields:
      - name: layout
        type: string
        default: post
      - name: title
        type: string
      - name: date
        type: string
        default: '{{now}}'
      - name: blurb
        type: string
      - name: og_image
        type: string
      - name: body
        type: rich-text